[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.MQTT]
        path = "credentials"
            [Writable.InsecureSecrets.MQTT.Secrets]
            username = ""
            password = ""

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49982
Protocol = 'http'
StartupMsg = 'device mqtt started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.edgex-core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.edgex-core-metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

[MessageQueue]
Enabled = false
Protocol = 'tcp'
Host = 'localhost'
Port = 1883
Type = 'mqtt'
PublishTopicPrefix = 'edgex/events' # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  # Client Identifiers
  ClientId = "device-mqtt"
  # Connection information
  Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive = "10" # Seconds (must be 2 or greater)
  Retained = "false"
  AutoReconnect = "true"
  ConnectTimeout = "5" # Seconds
  SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified
  ClientAuth = "none" # Valid values are: `none`, `usernamepassword` or `clientcert`
  Secretpath = "messagebus"  # Path in secret store used if ClientAuth not `none`

[SecretStore]
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/device-mqtt/'
Protocol = 'http'
RootCaCertPath = ''
ServerName = ''
TokenFile = '/tmp/edgex/secrets/device-mqtt/secrets-token.json'
AdditionalRetryAttempts = 10
RetryWaitPeriod = "1s"
    [SecretStore.Authentication]
    AuthType = 'X-Vault-Token'

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = ''
  DevicesDir = ''
  UpdateLastConnected = false

# Driver configs
[Driver]
IncomingSchema = 'tcp'
IncomingHost = '0.0.0.0'
IncomingPort = '1883'
IncomingQos = '0'
IncomingKeepAlive = '3600'
IncomingClientId = 'IncomingDataSubscriber'
IncomingTopic = 'DataTopic'
IncomingCredentialsPath = 'credentials'
ResponseSchema = 'tcp'
ResponseHost = '0.0.0.0'
ResponsePort = '1883'
ResponseQos = '0'
ResponseKeepAlive = '3600'
ResponseClientId = 'CommandResponseSubscriber'
ResponseTopic = 'ResponseTopic'
ResponseCredentialsPath = 'credentials'
CredentialsRetryTime = '120' # Seconds
CredentialsRetryWait = '1' # Seconds
ConnEstablishingRetry = '10'
ConnRetryWaitTime = '5'
